### ISSUE TITLE
not install

### ISSUE THREAD

**Issue by theone2025-3** [theraw/FOS-Streaming-v69#10]
not install error:
created admin table <br>
admin created: username: admin  and password: admin <br>
created categories table <br>
created category_user table <br>
created settings table <br>
created streams table <br>
created users table <br>
created transcodes table <br>
created transcode profile1 data <br>
created transcode profile2 data <br>
created activity table <br>
created blocked_ips table <br>
created blocked_user_agents table <br>
update <br>
crontab: usage error: no arguments permitted after this option
usage:  crontab [-u user] file
        crontab [ -u user ] [ -i ] { -e | -l | -r }
                (default operation is replace, per 1003.2)
        -e      (edit user's crontab)
        -l      (list user's crontab)
        -r      (delete user's crontab)
        -i      (prompt before deleting user's crontab)
root@halitv:~#

**Comment by theraw** [comment]
i don't remember adding crontab and looks like installation was finished successfully..
did you try to do something with crontab? i cannot see the command you have tried to execute that involves crontab i cannot help you. if you want to open crontab you need to use `sudo crontab -e`
