### ISSUE TITLE
Http 500 error

### ISSUE THREAD

**Issue by erdi2202** [theraw/FOS-Streaming-v69#11]
Hello, I am getting an error with php and fos streaming panel is not working. I am getting Http 500 error when trying to connect to the panel.

#5 /home/fos-streaming/fos/w" while reading response header from upstream, client: 176.237.218.65, server: , request: "POST /manage_stream.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "5.75.148.209:7777", referrer: "http://5.75.148.209:7777/manage_stream.php"
2022/12/05 17:03:44 [error] 2545#2545: *57 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property 'ffmpeg_path' of non-object in /home/fos-streaming/fos/www/cache/cdc3b756bded5c6b7056b8e12a5ca3efa135a1d6.php on line 25PHP message: PHP Notice:  Trying to get property 'ffprobe_path' of non-object in /home/fos-streaming/fos/www/cache/cdc3b756bded5c6b7056b8e12a5ca3efa135a1d6.php on line 32PHP message: PHP Notice:  Trying to get property 'webip' of non-object in /home/fos-streaming/fos/www/cache/cdc3b756bded5c6b7056b8e12a5ca3efa135a1d6.php on line 40PHP message: PHP Notice:  Trying to get property 'webport' of non-object in /home/fos-streaming/fos/www/cache/cdc3b756bded5c6b7056b8e12a5ca3efa135a1d6.php on line 49PHP message: PHP Notice:  Trying to get property 'hlsfolder' of non-object in /home/fos-streaming/fos/www/cache/cdc3b756bded5c6b7056b8e12a5ca3efa135a1d6.php on line 58PHP message: PHP Notice:  Trying to get property 'logourl' of non-object in /home/fos-streaming/fos/www/cache/cdc3b756bded5c6b7056b8e12a5ca3efa135a1d6.php on line 67PHP message: PHP Notice:  Trying to get property 'user_agent' of non-object in /home/fos-streaming/fos/www/cache/cdc3b756bded5c6b7056b8e12a5ca3efa135a1d6.php on line 76" while reading response header from upstream, client: 176.237.218.65, server: , request: "GET /settings.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "5.75.148.209:7777", referrer: "http://5.75.148.209:7777/streams.php"
2022/12/05 17:04:09 [error] 2545#2545: *59 FastCGI sent in stderr: "PHP message: PHP Warning:  Creating default object from empty value in /home/fos-streaming/fos/www/settings.php on line 9PHP message: PHP Notice:  Undefined property: stdClass::$webport in /home/fos-streaming/fos/www/settings.php on line 12PHP message: PHP Warning:  file_put_contents(/home/fos-streaming/fos/nginx/conf/nginx.conf): failed to open stream: Permission denied in /home/fos-streaming/fos/www/functions.php on line 330PHP message: PHP Warning:  mkdir(): No such file or directory in /home/fos-streaming/fos/www/settings.php on line 26PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::save() in /home/fos-streaming/fos/www/settings.php:31
Stack trace:
#0 {main}
  thrown in /home/fos-streaming/fos/www/settings.php on line 31" while reading response header from upstream, client: 176.237.218.65, server: , request: "POST /settings.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "5.75.148.209:7777", referrer: "http://5.75.148.209:7777/settings.php"

**Comment by theraw** [comment]
you have to install panel on a fresh instance don't try to install it on a machine where you have already installed something (php/mysql) or you will get such errors
this looks like your installation somehow is not complete and your mysql database is missing some data or a wrong php version.

**Comment by erdi2202** [comment]
When I try to install on a non-Mysql server, it gives an error during installation and the installation stops.

E: Package 'mysql-server' has no installation candidate
E: Package 'mysql-client' has no installation candidate

**Comment by theraw** [comment]
yeah well you can read the readme again

**Installation**
SUPPORTED DISTRO : Debian 9, 64 BIT
curl -s https://raw.githubusercontent.com/theraw/FOS-Streaming-v69/master/install/debian9 | bash
Visit : http://your-ip:7777/ login with User : admin Password : admin
Change "Web ip: *" with your public IPv4 server ip at http://your-ip:7777/settings.php
crontab -e */2 * * * * /etc/alternatives/php /home/fos-streaming/fos/www/cron.php
Mysql Password : cat /root/MYSQL_ROOT_PASSWORD

**Comment by theraw** [comment]
idk what you mean "non-mysql" but you need mysql to run this panel, if for some reason you cannot install mysql on your server then you can do it with custom mysql server aswell, if you already have installed your panel and only mysql data is missing then 

create one user to your database grab the passwords and add your mysql details to `/home/fos-streaming/fos/www/config.php`
then visit http://5.75.148.209:7777/install_database_tables.php?install and http://5.75.148.209:7777/install_database_tables.php?update

if you are running minimal debian 9 or something else or somehow you ran ```curl -s https://raw.githubusercontent.com/theraw/FOS-Streaming-v69/master/install/debian9 | bash``` and it failed to install mysql then let me know..
