### ISSUE TITLE
Proxy Mode

### ISSUE THREAD

**Issue by Marthinius** [theraw/FOS-Streaming-v69#3]
Hello,

How can I use it  in proxy mode ? 

I tried importing a playlist with proxy mode ticket. But nothing happened when trying to play stream.
I tried "no transcode" mode then all default mode, nothing happend. (stream is not playing)

**Comment by theraw** [comment]
if you can't provide any kind of error type/log/details i cannot guess by myself what's wrong with your setup.

Also i'm not providing support for this is just updated installation scripts

**Comment by Marthinius** [comment]
When I select the default options the stream plays. But no stream can be started through the proxy (without ffmpeg transcode sure).
error:

`*608 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property 'name' of non-object in /home/fos-streaming/fos/www/cache/fffb2504fcc0261c102647557629dbe323a90225.php on line 35PHP message: PHP Notice:  Trying to get property 'name' of non-object in /home/fos-streaming/fos/www/cache/fffb2504fcc0261c102647557629dbe323a90225.php on line 35" while reading response header from upstream, client: 192.168.1.2, server: , request: "GET /activities.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "192.168.1.1:xxxx", referrer: "http://192.168.1.1:xxxx/streams.php"`

**Comment by theraw** [comment]
this is not a error related with your current problem. is a php notice.

make sure you've set your public static server IPv4 to `http://your-ip:7777/settings.php` or the `m3u` that you will download will be downloaded with your server private ip which cannot access remotely.

Second problem could be unsupported audio/video format from your link/s source. i tried with and without transcode to re-stream this link source `https://dai.google.com/linear/hls/event/3dbJrQmVT_-psb-KBYuKQA/master.m3u8`
![image](https://user-images.githubusercontent.com/32969774/92761828-554b6280-f392-11ea-89c2-f76a9cf4d04d.png)
![image](https://user-images.githubusercontent.com/32969774/92761887-61372480-f392-11ea-81b7-973ba271965d.png)

in both cases i had no problems
![image](https://user-images.githubusercontent.com/32969774/92762028-8166e380-f392-11ea-9e38-de69f6107baa.png)


if with transcode is working it means that your backend link source is not possible to be live without encoding on a proper format

**Comment by Marthinius** [comment]
I understand, everything works (me too). Only the proxy option does not work see the picture example:

![import](https://user-images.githubusercontent.com/35543561/92890791-be28ee00-f417-11ea-8a55-198daa414b36.PNG)

![streams](https://user-images.githubusercontent.com/35543561/92891606-5aeb8b80-f418-11ea-9a01-c4ced609a04d.PNG)

**Comment by theraw** [comment]
That's a single stream, Create it as a stream and don't use playlist importer
