### ISSUE TITLE
I can't find rtmp configuration file

### ISSUE THREAD

**Issue by v-7-3** [theraw/FOS-Streaming-v69#6]
Please help me find it

**Comment by theraw** [comment]
this panel is an restreamer meaning it can re stream from your iptv reseller account so you have to put good tv links so you can sell them to your clients, 

That also means that there is no RTMP server, its just re streamer for multi-clients.

**Comment by v-7-3** [comment]
Yes, I want to use it to broadcast to RTMP servers

**Comment by theraw** [comment]
i'm not understanding what are you trying to do explain?

**Comment by v-7-3** [comment]
I am looking for a panel to send broadcasts to rtmp servers

**Comment by theraw** [comment]
you already said that, i mean explain your case on how. so i can give a better response.

what do you actually need this panel to do

**Comment by v-7-3** [comment]
I wanted to modify this format
  application live {
             live on;
             record off;

             push rtmp: // server-1: 1935 / live;
             push rtmp: // server-2: 1935 / live;
             push rtmp: // server-3: 1935 / live;
         }
But I couldn't find rtmp configuration file

**Comment by v-7-3** [comment]
I do not know English well

**Comment by v-7-3** [comment]
I mean, I want to send the broadcast to another server, not on the same server

**Comment by theraw** [comment]
nginx for this panel comes with RTMP module, https://github.com/theraw/fospackv69/blob/master/nginx-builder/build.sh#L41

so how to create a rtmp on your current nginx config?
open `/home/fos-streaming/fos/nginx/conf/nginx.conf `
and add your rtmp server config example
```
rtmp {
	server {
		listen 1935;
		chunk_size 88192;

		application live {
			live on;
                        record off;

			# hls on;
			# hls_nested on;
			# hls_path /hostdata/live_stream/public_html/hls;

                        push rtmp://a.rtmp.youtube.com/live2/XXXXXXXXXXXXXXXXXXXX;
		}
	}
}
```
and execute `service nginx restart`
then your rtmp server will be running on port `:1935` and the video you stream to that port will be sent to the "push ..."

this is a example https://github.com/theraw/my-nginx/blob/master/nginx-as-stream-server/nginx/nginx.conf

**Comment by theraw** [comment]
once you manually edit `/home/fos-streaming/fos/nginx/conf/nginx.conf` don't change server port or any other config from web dashboard on panel settings because it will reset nginx.conf to its default values and the changes you did manually will be lost.

**Comment by v-7-3** [comment]
Thank you very much, you are a good man
Thus, it means an existing any broadcast on the  panel will be sent to my rtmp server

**Comment by theraw** [comment]
yes the broadcast you sent to your rtmp server will be sent to example youtube  `push rtmp://a.rtmp.youtube.com/live2/XXXXXXX;`

**Comment by v-7-3** [comment]
Well I'll try my brother and thank you very much

**Comment by v-7-3** [comment]
you mean, now I add the broadcast using a board, and the broadcast will be sent to YouTube

**Comment by theraw** [comment]
dude you broadcast to your server where you have installed nginx/Fos-Streaming and nginx will push your broadcast anywhere you want i took as example youtube but you can push it to another place example twitch or whatever idk what you want to do that's why i asked you since the begin.

**Comment by v-7-3** [comment]
Okay thanks and sorry for the inconvenience. you help of me so much

**Comment by v-7-3** [comment]
I just don’t want to use obs, for example, to send broadcast. I just want to use  panel

**Comment by theraw** [comment]
you don't need to use obs to stream movies or small video files you can use ffmpeg.
